// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:better_keep/services/firebase_emulator_config.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kDebugMode, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  // Firestore emulator only supports (default) database, so use it when using emulators
  // In debug mode with "Live" selected, use the production database
  static String get databaseId {
    if (kDebugMode && FirebaseEmulatorConfig.isUsingEmulators) {
      return '(default)';
    }
    return 'better-keep';
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'Firebase does not officially support Linux desktop yet.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('WEB_API_KEY'),
    appId: String.fromEnvironment('WEB_APP_ID'),
    messagingSenderId: String.fromEnvironment('WEB_MESSAGING_SENDER_ID'),
    projectId: String.fromEnvironment('WEB_PROJECT_ID'),
    authDomain: String.fromEnvironment('WEB_AUTH_DOMAIN'),
    storageBucket: String.fromEnvironment('WEB_STORAGE_BUCKET'),
    measurementId: String.fromEnvironment('WEB_MEASUREMENT_ID'),
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('ANDROID_API_KEY'),
    appId: String.fromEnvironment('ANDROID_APP_ID'),
    messagingSenderId: String.fromEnvironment('ANDROID_MESSAGING_SENDER_ID'),
    projectId: String.fromEnvironment('ANDROID_PROJECT_ID'),
    authDomain: String.fromEnvironment(
      'ANDROID_AUTH_DOMAIN',
      defaultValue: 'betterkeep.app',
    ),
    storageBucket: String.fromEnvironment('ANDROID_STORAGE_BUCKET'),
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('WINDOWS_API_KEY'),
    appId: String.fromEnvironment('WINDOWS_APP_ID'),
    messagingSenderId: String.fromEnvironment('WINDOWS_MESSAGING_SENDER_ID'),
    projectId: String.fromEnvironment('WINDOWS_PROJECT_ID'),
    authDomain: String.fromEnvironment('WINDOWS_AUTH_DOMAIN'),
    storageBucket: String.fromEnvironment('WINDOWS_STORAGE_BUCKET'),
    measurementId: String.fromEnvironment('WINDOWS_MEASUREMENT_ID'),
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('IOS_API_KEY'),
    appId: String.fromEnvironment('IOS_APP_ID'),
    messagingSenderId: String.fromEnvironment('IOS_MESSAGING_SENDER_ID'),
    projectId: String.fromEnvironment('IOS_PROJECT_ID'),
    authDomain: String.fromEnvironment(
      'IOS_AUTH_DOMAIN',
      defaultValue: 'betterkeep.app',
    ),
    storageBucket: String.fromEnvironment('IOS_STORAGE_BUCKET'),
    iosClientId: String.fromEnvironment('IOS_CLIENT_ID'),
    iosBundleId: String.fromEnvironment('IOS_BUNDLE_ID'),
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('MACOS_API_KEY'),
    appId: String.fromEnvironment('MACOS_APP_ID'),
    messagingSenderId: String.fromEnvironment('MACOS_MESSAGING_SENDER_ID'),
    projectId: String.fromEnvironment('MACOS_PROJECT_ID'),
    authDomain: String.fromEnvironment(
      'MACOS_AUTH_DOMAIN',
      defaultValue: 'betterkeep.app',
    ),
    storageBucket: String.fromEnvironment('MACOS_STORAGE_BUCKET'),
    iosClientId: String.fromEnvironment('MACOS_CLIENT_ID'),
    iosBundleId: String.fromEnvironment('MACOS_BUNDLE_ID'),
  );

  // Linux is not supported by Firebase yet
  // See: https://firebase.google.com/docs/flutter/setup
}
